### ISSUE TITLE
px-datetime-entry: rendering issue in IE11 and FF.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-rangepicker#53] opened 2017-12-21 18:03 UTC
### Expected behavior and actual behavior:
Rendering issues in IE11 and FF57, cells cut off to only allow one character.
See Screenshot below.

### Environment:
Browsers: IE11, FF57
Rangepicker Version: 3.0.0

### Screenshot:
<img width="1301" alt="screen shot 2017-12-21 at 10 01 28 am" src="https://user-images.githubusercontent.com/10835611/34268538-fccdc72c-e635-11e7-9b94-9a60a5162d03.png">

**Comment by benoitjchevalier** [comment] 2017-12-21 18:16
duplicate of https://github.com/PredixDev/px-datetime-common/issues/13

**Comment by randyaskin** [comment] 2018-01-03 21:37
Appears to have NOT been fixed in Q4'17 refactor - still an issue in FF at least.

**Closed** 2019-03-04 03:29 UTC
Labels: browser bug, wontfix
